import type { EvidenceChannel, FindingSeverity } from "../analyses/analysis.types.js";

export type PatternDefinition = {
  patternId: string;
  category: string;
  name: string;
  description: string;
  indicators: {
    anyFindingCodes: string[];
    allFindingCodes?: string[];
    entityKinds?: string[];
    minMatchedIndicators: number;
  };
  severity: FindingSeverity;
  applicableChannels: EvidenceChannel[];
  recommendedProtectiveActions: string[];
  aliases: string[];
  examples: string[];
  version: string;
};

/**
 * Versioned, data-shaped starter taxonomy. Detection routes never encode these
 * combinations directly; this set can be replaced/extended through moderation.
 */
export const builtInPatternTaxonomy: PatternDefinition[] = [
  {
    patternId: "bank_payment_impersonation",
    category: "bank_payment_impersonation",
    name: "Bank or payment-provider impersonation",
    description: "A message claims to represent a financial organization while pressuring a person to act, pay, or share credentials.",
    indicators: { anyFindingCodes: ["authority_impersonation_language", "account_security_warning"], allFindingCodes: ["urgency_pressure"], entityKinds: ["payment_handle", "url"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["sms", "email", "chat", "phone_call"],
    recommendedProtectiveActions: ["do_not_share_credentials", "do_not_pay", "contact_independently", "open_official_app"],
    aliases: ["bank alert", "payment app alert", "account blocked"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "kyc_account_warning",
    category: "kyc_account_warning",
    name: "KYC or account-warning lure",
    description: "A claimed account verification or KYC issue directs a person to act through a supplied link or contact method.",
    indicators: { anyFindingCodes: ["account_security_warning", "fear_or_threat_language", "url_sensitive_theme"], entityKinds: ["url"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["sms", "email", "chat"],
    recommendedProtectiveActions: ["open_official_app", "do_not_click", "contact_independently"],
    aliases: ["KYC expired", "account verification"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "delivery_courier_fee",
    category: "delivery_courier",
    name: "Delivery or courier fee lure",
    description: "A parcel, shipment, customs, or delivery update pairs with a link or payment request.",
    indicators: { anyFindingCodes: ["delivery_or_refund_pattern", "unusual_payment_request", "url_shortener", "url_sensitive_theme"], minMatchedIndicators: 2 },
    severity: "medium",
    applicableChannels: ["sms", "email", "chat"],
    recommendedProtectiveActions: ["open_official_app", "do_not_click", "do_not_pay"],
    aliases: ["parcel fee", "courier delivery"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "job_recruitment_advance_fee",
    category: "job_recruitment",
    name: "Job recruitment advance-fee pattern",
    description: "A job or recruitment offer asks for money, registration, training, or a deposit before employment.",
    indicators: { anyFindingCodes: ["job_payment_pattern", "unusual_payment_request", "urgency_pressure"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["email", "chat", "social_media", "marketplace"],
    recommendedProtectiveActions: ["do_not_pay", "verify_company_independently", "preserve_evidence"],
    aliases: ["work from home fee", "recruiter deposit"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "investment_return_promise",
    category: "investment",
    name: "Guaranteed-return investment lure",
    description: "A financial opportunity promises unusually certain returns or pressure to invest quickly.",
    indicators: { anyFindingCodes: ["investment_return_claim", "unusual_payment_request", "urgency_pressure"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["chat", "social_media", "phone_call", "website"],
    recommendedProtectiveActions: ["do_not_pay", "pause_and_verify", "preserve_evidence"],
    aliases: ["guaranteed profit", "daily return"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "marketplace_payment_diversion",
    category: "marketplace",
    name: "Marketplace payment diversion",
    description: "A marketplace interaction asks a buyer or seller to pay or communicate outside the normal platform process.",
    indicators: { anyFindingCodes: ["unusual_payment_request", "verification_bypass_request", "urgency_pressure"], entityKinds: ["payment_handle", "url"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["marketplace", "chat"],
    recommendedProtectiveActions: ["do_not_pay", "use_platform_only", "preserve_evidence"],
    aliases: ["off-platform payment", "marketplace courier"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "romance_social_manipulation",
    category: "romance_social_engineering",
    name: "Social manipulation with secrecy or payment pressure",
    description: "A social contact seeks secrecy, urgent help, or financial transfer without an independently verifiable reason.",
    indicators: { anyFindingCodes: ["secrecy_instruction", "unusual_payment_request", "urgency_pressure"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["social_media", "chat", "phone_call"],
    recommendedProtectiveActions: ["do_not_pay", "pause_and_verify", "talk_to_someone_trusted"],
    aliases: ["emergency money request", "secret relationship"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "government_authority_impersonation",
    category: "government_authority_impersonation",
    name: "Government or authority impersonation",
    description: "A sender claims official authority and uses threats, urgency, or payment demands.",
    indicators: { anyFindingCodes: ["authority_impersonation_language", "fear_or_threat_language", "unusual_payment_request"], minMatchedIndicators: 2 },
    severity: "critical",
    applicableChannels: ["sms", "email", "phone_call", "chat"],
    recommendedProtectiveActions: ["do_not_pay", "contact_independently", "preserve_evidence"],
    aliases: ["police call", "tax department notice"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "tech_support_remote_access",
    category: "tech_support",
    name: "Tech-support remote-access attempt",
    description: "A claimed support interaction asks a person to install remote-access software or share their screen.",
    indicators: { anyFindingCodes: ["remote_access_request", "authority_impersonation_language"], minMatchedIndicators: 1 },
    severity: "critical",
    applicableChannels: ["phone_call", "website", "chat", "email"],
    recommendedProtectiveActions: ["do_not_install_software", "disconnect_if_connected", "contact_independently"],
    aliases: ["remote support", "screen share support"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "refund_chargeback_lure",
    category: "refund_chargeback",
    name: "Refund or chargeback lure",
    description: "A refund promise directs someone to a link, an unfamiliar app, or a payment/credential action.",
    indicators: { anyFindingCodes: ["delivery_or_refund_pattern", "unusual_payment_request", "credential_or_otp_request", "remote_access_request"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["sms", "email", "phone_call", "chat"],
    recommendedProtectiveActions: ["do_not_click", "do_not_share_credentials", "open_official_app"],
    aliases: ["refund fraud", "chargeback callback"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "prize_reward_fee",
    category: "prize_reward",
    name: "Prize or reward fee lure",
    description: "An unexpected reward or prize is paired with an advance payment or sensitive-information request.",
    indicators: { anyFindingCodes: ["reward_or_prize_bait", "unusual_payment_request", "sensitive_data_request"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["sms", "email", "social_media", "chat"],
    recommendedProtectiveActions: ["do_not_pay", "do_not_share_credentials", "pause_and_verify"],
    aliases: ["lottery fee", "reward claim"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "loan_credit_advance_fee",
    category: "loan_credit",
    name: "Loan or credit advance-fee pattern",
    description: "A loan or credit offer asks for a processing, insurance, or release fee before funds are available.",
    indicators: { anyFindingCodes: ["unusual_payment_request", "urgency_pressure"], entityKinds: ["amount", "payment_handle"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["sms", "email", "chat", "social_media"],
    recommendedProtectiveActions: ["do_not_pay", "verify_company_independently"],
    aliases: ["loan release fee", "instant credit"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "otp_credential_theft",
    category: "otp_credential_theft",
    name: "OTP or credential theft attempt",
    description: "A sender requests an OTP, password, PIN, or similarly sensitive credential.",
    indicators: { anyFindingCodes: ["credential_or_otp_request", "sensitive_data_request"], minMatchedIndicators: 1 },
    severity: "critical",
    applicableChannels: ["sms", "email", "chat", "phone_call", "social_media"],
    recommendedProtectiveActions: ["do_not_share_credentials", "contact_independently", "change_password_if_shared"],
    aliases: ["OTP scam", "password request"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "remote_access_scam",
    category: "remote_access",
    name: "Remote-access scam",
    description: "A sender attempts to control or observe a device using screen-sharing or remote-control software.",
    indicators: { anyFindingCodes: ["remote_access_request", "verification_bypass_request"], minMatchedIndicators: 1 },
    severity: "critical",
    applicableChannels: ["phone_call", "chat", "website"],
    recommendedProtectiveActions: ["do_not_install_software", "disconnect_if_connected", "secure_accounts"],
    aliases: ["AnyDesk scam", "screen-share scam"],
    examples: [],
    version: "1.0.0",
  },
  {
    patternId: "crypto_payment_scam",
    category: "crypto_payment",
    name: "Crypto or irreversible-payment pressure",
    description: "A sender uses crypto, gift cards, or other difficult-to-reverse payment methods with pressure or authority claims.",
    indicators: { anyFindingCodes: ["unusual_payment_request", "urgency_pressure", "authority_impersonation_language"], minMatchedIndicators: 2 },
    severity: "high",
    applicableChannels: ["chat", "social_media", "phone_call", "email"],
    recommendedProtectiveActions: ["do_not_pay", "preserve_evidence", "contact_independently"],
    aliases: ["crypto payment", "gift card payment"],
    examples: [],
    version: "1.0.0",
  },
];
